{% set version = "0.8.2" %}

package:
  name: theano
  version: {{ version }}

source:
  fn: Theano-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/30/3d/2354fac96ca9594b755ec22d91133522a7db0caa0877165a522337d0ed73/Theano-{{ version }}.tar.gz
  md5: f2d0dfe7df141115201077cd933b2c52

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7.1
    - scipy >=0.11
    - six >=1.9.0
  run:
    - python
    - numpy >=1.7.1
    - scipy >=0.11
    - six >=1.9.0

test:
  imports:
    - theano
    - theano.compat
    - theano.compile
    - theano.compile.sandbox
    - theano.compile.tests
    - theano.d3viz
    - theano.d3viz.tests
    - theano.gof
    - theano.gof.tests
    - theano.misc
    - theano.misc.tests
    - theano.sandbox
    - theano.sandbox.cuda
    - theano.sandbox.cuda.tests
    - theano.sandbox.gpuarray
    - theano.sandbox.gpuarray.tests
    - theano.sandbox.linalg
    - theano.sandbox.linalg.tests
    - theano.sandbox.tests
    - theano.scalar
    - theano.scalar.tests
    - theano.scan_module
    - theano.scan_module.tests
    - theano.sparse
    - theano.sparse.sandbox
    - theano.sparse.tests
    - theano.tensor
    - theano.tensor.nnet
    - theano.tensor.nnet.tests
    - theano.tensor.signal
    - theano.tensor.signal.tests
    - theano.tensor.tests
    - theano.tests
    - theano.typed_list
    - theano.typed_list.tests
  requires:
    - nose >=1.3.0
    - nose-parameterized >=0.5.0

about:
  home: http://deeplearning.net/software/theano/
  license: BSD
  summary: Optimizing compiler for evaluating mathematical expressions
  description: |
    Theano is a Python library that allows you to define, optimize, and
    efficiently evaluate mathematical expressions involving multi-dimensional
    arrays. It is built on top of NumPy.
  doc_url: http://deeplearning.net/software/theano/
  dev_url: https://github.com/Theano/Theano
